[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]
##############################
# >>> Hatch Build Config <<< #
##############################

[project]
name = "reactpy-utils"
description = "A ReactPy component package"
readme = "README.md"
keywords = ["React", "ReactJS", "ReactPy", "components"]
license = "MIT"
authors = [{ name = "Steve Jones", email = "jonesst2608@gmail.com" }]
requires-python = ">=3.9"
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "reactpy==2.0.0b7",
  "reactpy-router @ https://raw.githubusercontent.com/stevej2608/reactpy-router/2.0.1b7/dist/reactpy_router-2.0.1b7-py3-none-any.whl",

  ]
dynamic = ["version"]
urls.Homepage = "https://github.com/stevej2608/reactpy-utils"
urls.Source = "https://github.com/stevej2608/reactpy-utils"

[tool.hatch.version]
path = "src/reactpy_utils/__init__.py"

[tool.hatch.build.targets.sdist]
include = ["/src", "/tests", "/examples", "/utils"]
[tool.hatch.build.targets.wheel]
packages = ["src/reactpy_utils"]
[tool.hatch.metadata]
license-files = { paths = ["LICENSE"] }
allow-direct-references = true

[tool.hatch.envs.default]
installer = "uv"

#############################
# >>> Hatch Test Runner <<< #
#############################

[tool.hatch.envs.hatch-test]
extra-dependencies = [
  "asgi-tools",
  "asgiref",
  "cryptography",
  "exceptiongroup",
  "lorem",
  "orjson",
  "pillow",
  "pixelmatch",
  "playwright",
  "pydantic",
  "pyright",
  "pytest-asyncio",
  "pytest-sugar",
  "servestatic",
  "uvicorn[standard]",
]
randomize = true
matrix-name-format = "{variable}-{value}"

[[tool.hatch.envs.hatch-test.matrix]]
python = ["3.11", "3.12", "3.13", "3.14"]

[tool.pytest.ini_options]
testpaths = "tests"
log_cli_level = "INFO"
filterwarnings = "ignore::DeprecationWarning"
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"

################################
# >>> Hatch Python Scripts <<< #
################################

[tool.hatch.envs.python]
extra-dependencies = ["pyright"]

[tool.hatch.envs.python.scripts]
type_check = ["pyright reactpy_utils"]

#######################################
# >>> Hatch Documentation Scripts <<< #
#######################################

[tool.hatch.envs.docs]
template = "docs"
detached = true
dependencies = [
  "mkdocs",
  "mkdocs-git-revision-date-localized-plugin",
  "mkdocs-material==9.4.0",
  "mkdocs-include-markdown-plugin",
  "linkcheckmd",
  "mkdocs-spellcheck[all]",
  "mkdocs-git-authors-plugin",
  "mkdocs-minify-plugin",
  "mike",
  "mkdocstrings[python]",
  "black",
  "reactpy_utils @ {root:uri}",
]

[tool.hatch.envs.docs.scripts]
serve = ["cd docs && mkdocs serve"]
build = ["cd docs && mkdocs build --strict"]

#########################
# >>> Generic Tools <<< #
#########################

[tool.ruff]
# https://docs.astral.sh/ruff/configuration/
# https://marketplace.visualstudio.com/items?itemName=charliermarsh.ruff
line-length = 120

[tool.pyright]
# https://github.com/microsoft/pyright/blob/main/docs/configuration.md#sample-pyprojecttoml-file
typeCheckingMode = "standard"
pythonVersion = "3.11"
reportMissingTypeStubs = false
ignore = ["tmp", "tmp/**", "**/tmp/**"]
