blank_issues_enabled: false
contact_links:
    - name: Start a Discussion
      url: https://github.com/stevej2608/reactpy-utils/discussions
      about: Report issues, request features, ask questions, and share ideas
