---
nav:
  - Get Started:
      - Overview: index.md
  - Components:
      - Clipboard: components/clipboard.md
      - Document Title: components/document_title.md
      - Local Storage: components/local_storage.md
  - About:
      - Changelog: about/changelog.md
      - Contributor Guide: about/contributing.md
      - License: about/license.md

theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
      primary: red # We use red to indicate that something is unthemed
      accent: red
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: white
      accent: red
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - content.code.copy
    - search.highlight
  icon:
    repo: fontawesome/brands/github
    admonition:
      note: fontawesome/solid/note-sticky
  logo: assets/image/logo-toolbox.svg
  favicon: assets/image/logo-toolbox.svg

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.inlinehilite
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.keys

plugins:
  - search
  - include-markdown
  - git-authors
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      cache_safe: true
  - git-revision-date-localized:
      fallback_to_build_date: true
  - spellcheck:
      known_words: dictionary.txt
      allow_unicode: no
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: ["../"]
          import:
            - https://reactpy.dev/docs/objects.inv
            - https://installer.readthedocs.io/en/stable/objects.inv
          options:
            signature_crossrefs: true
            scoped_crossrefs: true
            relative_crossrefs: true
            modernize_annotations: true
            unwrap_annotated: true
            find_stubs_package: true
            show_root_members_full_path: true
            show_bases: false
            show_source: false
            show_root_toc_entry: false
            show_labels: false
            show_symbol_type_toc: true
            show_symbol_type_heading: true
            show_object_full_path: true
            heading_level: 3
extra:
  generator: false
  version:
    provider: mike
  analytics:
    provider: google
    property: G-XRLQYZBG00

extra_javascript:
  - assets/js/main.js

extra_css:
  - assets/css/main.css
  - assets/css/button.css
  - assets/css/admonition.css
  - assets/css/banner.css
  - assets/css/sidebar.css
  - assets/css/navbar.css
  - assets/css/table-of-contents.css
  - assets/css/code.css
  - assets/css/footer.css
  - assets/css/home.css

watch:
  - "../docs"
  - ../README.md
  - ../CHANGELOG.md
  - ../LICENSE.md
  - "../src"

site_name: ReactPy Utils
site_author: Steve Jones
site_description: It's React-Router, but in Python.
copyright: '&copy;<div id="year"> </div> <script> document.getElementById("year").innerHTML = new Date().getFullYear(); </script>Reactive Python and affiliates.<div class="legal-footer-right">This project has no affiliation to ReactJS or Meta Platforms, Inc.</div>'
repo_url: https://github.com/jonesst2608/reactpy-utils
site_url: https://jonesst2608.github.io/reactpy-utils
repo_name: ReactPy Utils (GitHub)
edit_uri: edit/main/docs/src/
docs_dir: src
